volumes:
  lavinmq: null
  postgres: null

services:
  postgres:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  lavinmq:
    image: cloudamqp/lavinmq
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - lavinmq:/var/lib/lavinmq
  strapi:
    build: ../../admin
    restart: unless-stopped
    shm_size: 128mb
    depends_on:
      - postgres
      - lavinmq
    environment: {}
  bot:
    build: ../../bot
    restart: unless-stopped
    shm_size: 128mb
    depends_on:
      - strapi
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      API_TOKEN: ${API_TOKEN}
      API_URL: http://strapi/api
      AMQP_URL: amqp://guest:guest@lavinmq

